### PR TITLE
Support new NWC commands

### LINKED ISSUE #895: Improve NWC support (return response from send payment, get_balance, make_invoice/lookup_invoice)
Hi, we added a mutiny wallet connector to Bitcoin Connect so you can connect to your wallet in any lightning webapp and seamlessly execute lightning functionality, as long as the wallet is open on a second device (e.g. keep the Mutiny wallet open on your PC and then use Bitcoin Connect to connect to it on your phone).

Unfortunately there are some issues: 
- Send Payment works, but it seems Mutiny Wallet never sends a response event, or at least not within 60 seconds. I had the wallet open on my phone and it marked the payment as sent within 20 seconds or so.
- Get Balance and Make invoice just don't seem to be supported at all?

I created an issue here: https://github.com/getAlby/bitcoin-connect/issues/150

### PR DESCRIPTION
**Pull request by benthecarman**
This adds support for `get_balance`, `get_info`, `make_invoice`, and `lookup_invoice`.

Currently missing the multi commands as they'd require a larger refactor that I'd rather do as a follow up. Also left out keysends because that'd require a refactor for budgeting and `list_transactions` because I am not sure how we'd want to implement that while preserving privacy.

Closes #895

### CODE REVIEW

**Comment by TonyGiorgio** [comment]
needs rebase

**Comment by TonyGiorgio** [comment]
Failing tests

**Comment by TonyGiorgio** [comment]
needs rebase

**Comment by TonyGiorgio** [comment]
`This adds support for get_balance, get_info, make_invoice, and lookup_invoice.` 

These should probably be allowed by default

**Comment by benthecarman** [comment]
> These should probably be allowed by default

Done

**Review by TonyGiorgio — APPROVED** [review]

**Comment by rolznz** [comment]
Cool! How can I test this? do I need to create a new connection? I tried to create one and get "Unknown error occurred" - auto approve, 10000 sats, resets daily

**Comment by benthecarman** [comment]
This hasn't been deployed yet, should be by the end of the month

**Comment by rolznz** [comment]
I tried the Mutiny latest update (PWA version) and am still having issues doing any requests outside of pay_invoice. Is it in this release?

I would love to see Mutiny working with some of the NWC-powered apps like the BuzzPay PoS https://github.com/getAlby/pos

**Comment by benthecarman** [comment]
If you make a new connection it should get the new commands.

**Comment by rolznz** [comment]
I tried again today. `make_invoice` works, but `lookup_invoice` never seems to be updated so the PoS never gets a confirmation of the payment (it polls lookup_invoice). My mutiny wallet was open and I received the payment there.

I updated the PoS to be more relaxed and will show a confirmation rather than erroring if the wrong NWC permissions are given. You should be able to try it: https://github.com/getAlby/pos

**Comment by benthecarman** [comment]
In the logs I am getting these errors after it is paid, seems like something on your end, that error message isn't from us
image

**Comment by rolznz** [comment]
@benthecarman that error happens when we get no reply from the wallet within a timeout. Can you check the reply payload you are sending?

**Comment by benthecarman** [comment]
hmm looks like `rust-nostr` is parsing for `bolt11` but the spec is `invoice` :man_facepalming: my bad

**Pull request merged**
