### PR TITLE
Get federation config from URL if available

### PR DESCRIPTION
**Pull request by TonyGiorgio**
@futurepaul can you test this out now? Should try to parse it correctly.

### CODE REVIEW

**Review by benthecarman — APPROVED** [review]
lgtm, should wait on @futurepaul though

**Comment by futurepaul** [comment]
I'll try this out now

**Comment by futurepaul** [comment]
still seeing nulls sry:

Screenshot 2024-05-07 at 7 43 52 PM

**Comment by TonyGiorgio** [comment]
Feel free to get in here and do it yourself, since you know how to test it and you know how to get it properly.

**Comment by futurepaul** [comment]
I'll give it a shot

**Comment by futurepaul** [comment]
This seems to work. No idea if I did the right thing in the merge_values section, I was just doing whatever the red squigglies told me to do

Screenshot 2024-05-08 at 11 18 27 AM

**Comment by TonyGiorgio** [comment]
Nice. Only thing that's not coming through is the `sites` parameter. I think it just needs to be turned to a `Vec` and it would work? Otherwise just remove it, we don't need it.

**Review by futurepaul — APPROVED** [review]
this is working well for me (I removed the sites thing)

**Pull request merged**
