### PR TITLE
Add comments to zaps & lnurl pay

### PR DESCRIPTION
**Pull request by benthecarman**

### CODE REVIEW

**Review by TonyGiorgio — CHANGES_REQUESTED** [review]
I'd prefer if you added it after labels in order to have less of a breaking change on the frontend.

**Review by TonyGiorgio — APPROVED** [review]
Thanks. Now it doesn't matter if the frontend updates or not, it'll treat it as None.

**Comment by TonyGiorgio** [comment]
what is the intended use case for this? changes look fine, I'm just curious what spurred this change?

**Comment by benthecarman** [comment]
Right now we have the `What's it for?` text on the new send screen, but it only labels it locally. With this we could send it in a zap/lnurl pay as well

**Comment by TonyGiorgio** [comment]
> Right now we have the `What's it for?` text on the new send screen, but it only labels it locally. With this we could send it in a zap/lnurl pay as well

Okay, that makes sense when differentiated between private & public zaps, so makes sense for some of the things we've discussed.

**Pull request merged**
