### PR TITLE
Make sure LSP url is a valid url when switching

### PR DESCRIPTION
**Pull request by benthecarman**

### CODE REVIEW

**Comment by TonyGiorgio** [comment]
still doesn't work

Screenshot 2024-06-10 at 8 00 35 PM

**Comment by benthecarman** [comment]
Main purpose of this wasn't to be able to get people out of this state but to prevent it from happening. Added some `trim()`s everywhere that should help get your wallet unstuck

**Comment by TonyGiorgio** [comment]
I used a new wallet and still got into this state.

**Comment by benthecarman** [comment]
Think this should prevent everywhere, otherwise plz lmk how you reproduce

**Review by TonyGiorgio — APPROVED** [review]

**Pull request merged**
