### PR TITLE
Wait for our fee estimates before connecting to peers

### PR DESCRIPTION
**Pull request by benthecarman**
Recommendation from @tnull

### CODE REVIEW

**Comment by TonyGiorgio** [comment]
>  just getting a fee rate estimation might be sufficient to fix the fee issues

Yeah let's try this instead if it's not too much of an issue. Paying invoices might start to really slow down if we're waiting on too many things. Especially syncing, which is a lot slower on mainnet.

**Comment by benthecarman** [comment]
this seems to break tests :/

**Comment by benthecarman** [comment]
Okay made it so we don't do the connection retrying on regtest

**Comment by TonyGiorgio** [comment]
> Okay made it so we don't do the connection retrying on regtest

Err, not sure about that. Can you just make it not do fee checking on regtest instead?

**Review by TonyGiorgio — APPROVED** [review]

**Pull request merged**
