### PR TITLE
Crates publish

### PR DESCRIPTION
**Pull request by TonyGiorgio**
I think this CI should work. Already published locally with the same cargo command: https://crates.io/crates/mutiny-core

### CODE REVIEW

**Comment by benthecarman** [comment]
ugh the CI issues you are getting are ugly, I thought I fixed that in master, might need to add more flags to the webdriver.json file

**Comment by TonyGiorgio** [comment]
I think it might be timeout related since not all the tests seem to be running, increased to 60s to test it out

**Comment by TonyGiorgio** [comment]
@benthecarman I increased timeout to 60s and it seems like these 3 tests are not making it in: 

```
test mutiny_core::gossip::test::test_merge_peer_info ... ok	
test mutiny_core::keymanager::tests::derive_pubkey_child_from_seed ... ok	
test mutiny_core::ldkstorage::test::test_persist_payment_info ... ok
```

Is there any significance to them? Were they the ones you were using? I can try commenting them out and seeing if that works.

**Comment by benthecarman** [comment]
> test mutiny_core::gossip::test::test_merge_peer_info ... ok	

should be a really fast test, don't know how that'd not be working. Maybe just need to bump the timeout

**Comment by TonyGiorgio** [comment]
Worked now, I'll start adding some back to see if it was just stalled on one of them.

**Comment by benthecarman** [comment]
@TonyGiorgio maybe try making `test_persist_payment_info` an async fn?

**Comment by TonyGiorgio** [comment]
> @TonyGiorgio maybe try making `test_persist_payment_info` an async fn?

Interesting, I'll try that next. Seems like it is something with `test_persist_payment_info`. I've added the cleanup function at the end of it, maybe that's conflicting.

**Comment by TonyGiorgio** [comment]
Do you think we need a cleanup for indexdb as well?

**Comment by benthecarman** [comment]
> Do you think we need a cleanup for indexdb as well?

Yeah that'd be good to add

**Review by benthecarman — APPROVED** [review]

**Pull request merged**
