### PR TITLE
Add waila to mutiny-wasm

### LINKED ISSUE #334: Integrate WAILA
We should add as a utility function for the front end

https://github.com/MutinyWallet/bitcoin-waila

### PR DESCRIPTION
**Pull request by benthecarman**
Closes #334

### CODE REVIEW

**Review by futurepaul — APPROVED** [review]
this looks good to me at a glance, high probability I'll have some needs going forward but gotta play with it to know for sure. one thing I'd like but isn't pressing is npub scanning

**Comment by TonyGiorgio** [comment]
Why just in the wasm package instead of `mutiny-core`?

**Comment by benthecarman** [comment]
> Why just in the wasm package instead of mutiny-core?

Anywhere else we can just call the actual library when we need it, this is just a wasm bindgen wrapper for the library basically.

**Comment by TonyGiorgio** [comment]
Wouldn't it make more sense to have `waila` be a wasm ts package on it's own then?

**Comment by benthecarman** [comment]
> Wouldn't it make more sense to have waila be a wasm ts package on it's own then?

That's a good point

**Comment by TonyGiorgio** [comment]
I can see that being annoying, but if we're not going to use it elsewhere and there's going to be increasing things that only the frontend wants to use for it then I can see keeping it as a dedicated package on it's own. Otherwise, if `mutiny-core` will use it, I can see putting it in there and wrapping it in `mutiny-wasm`.

**Pull request closed without merging**
