### PR TITLE
Filter out StaticOutput spendable outputs

### PR DESCRIPTION
**Pull request by benthecarman**
Part of #433

We can filter out the `StaticOutput`s because these are just the utxos that already went to our BDK wallet, there's no reason to spend them back into our BDK wallet.

### CODE REVIEW

**Review by TonyGiorgio — CHANGES_REQUESTED** [review]
There's another reason for the panics as well, we are passing an empty vec of outputs.

```
                let spending_tx = self
                    .keys_manager
                    .spend_spendable_outputs(
                        output_descriptors,
                        Vec::new(),
                        tx_feerate,
                        &Secp256k1::new(),
                    )
                    .expect("could not spend spendable outputs");
```

**Comment by benthecarman** [comment]
> There's another reason for the panics as well, we are passing an empty vec of outputs.

That is just any extra outputs we want to add on (like if we wanted to do a payment or something). Since we put an empty vec everything will just be swept to our change address.

**Comment by TonyGiorgio** [comment]
> > There's another reason for the panics as well, we are passing an empty vec of outputs.
> 
> That is just any extra outputs we want to add on (like if we wanted to do a payment or something). Since we put an empty vec everything will just be swept to our change address.

Is that because we provided our change addresses in a `keys_manager` function?

**Comment by benthecarman** [comment]
> Is that because we provided our change addresses in a keys_manager function?

Yes

**Review by TonyGiorgio — APPROVED** [review]
Looks good!

**Pull request merged**
