### PR TITLE
Rework wasm apis for Contacts

### PR DESCRIPTION
**Pull request by benthecarman**
Requested by @futurepaul 

Removed the `Contact` struct and just using the `TagItem` struct instead, they contain the same info besides `TagItem` has the `id`, which was the main problem with `Contact`

### CODE REVIEW

**Review by futurepaul — CHANGES_REQUESTED** [review]
looks like you hardcoded image_url to None, need to add that to TagItem

**Comment by TonyGiorgio** [comment]
Code looks good. Is this going to work with existing tags / contacts though? Should double check a before and after.

**Comment by benthecarman** [comment]
> Code looks good. Is this going to work with existing tags / contacts though? Should double check a before and after.

it should, this is just the api layer on top of the internal logic. Lets wait for paul to finish building on top before we merge though

**Comment by benthecarman** [comment]
> looks like you hardcoded image_url to None, need to add that to TagItem

fixed

**Review by futurepaul — APPROVED** [review]
worked for me!

**Comment by futurepaul** [comment]
can we merge this and cut an npm release? want to start using this for the new send stuff. (this allows me to look up a single contact by id)

**Comment by benthecarman** [comment]
> can we merge this and cut an npm release? want to start using this for the new send stuff. (this allows me to look up a single contact by id)

sgtm maybe get in #904 as well so we can have the multi lsp stuff working too

**Pull request merged**
