### PR TITLE
Parse bech32 and hex npubs

### PR DESCRIPTION
**Pull request by benthecarman**
requested by @futurepaul

### CODE REVIEW

**Comment by futurepaul** [comment]
looks like this is still returning the hex version for contacts?

Screenshot 2024-01-05 at 4 16 21 PM

**Comment by benthecarman** [comment]
Oh will add that

**Comment by benthecarman** [comment]
@futurepaul added

**Comment by futurepaul** [comment]
sry still seems to be returning the hexpub

**Comment by benthecarman** [comment]
Okay think i fixed it

**Review by futurepaul — APPROVED** [review]
works for me!

**Pull request merged**
