### PR TITLE
Show gateway_fee in FederationIdentity

### PR DESCRIPTION
**Pull request by TonyGiorgio**

### CODE REVIEW

**Review by benthecarman — APPROVED** [review]

**Comment by TonyGiorgio** [comment]
Will wait for a comment from @futurepaul , this is for him

**Review by futurepaul — COMMENTED** [review]
this looks good to me data-wise, although I don't see any code in mutiny-wasm so not sure it will show up for the frontend?

also, if we could add a convenience method called `get_estimated_fee` and I can just put in an mount and get an `Option<u64>` of your best guess, I can display that as "estimated fee"

**Comment by TonyGiorgio** [comment]
> although I don't see any code in mutiny-wasm so not sure it will show up for the frontend?

Good catch, I assumed it was pulling it for conversion but it's not.

**Comment by benthecarman** [comment]
Done in #995

**Pull request closed without merging**
