### PR TITLE
bdk-alpha1

### PR DESCRIPTION
**Pull request by benthecarman**
Release is coming up soon, wanted to see how big the changes would be, found a few things that they are gonna make PRs in BDK for before releasing. Otherwise, want to test to make sure that previous wallets dont break and that new wallets work well.

### CODE REVIEW

**Review by TonyGiorgio — COMMENTED** [review]
I remember there was a TODO somewhere once this released. Something about putting all broadcasted transactions into the wallet db?

**Comment by benthecarman** [comment]
Looks like this works for previous wallets and new wallets :)

**Comment by benthecarman** [comment]
> I remember there was a TODO somewhere once this released. Something about putting all broadcasted transactions into the wallet db?

fixed

**Comment by TonyGiorgio** [comment]
On both browsers I have opened with existing state (some channel closes and force channel closes), I get `Error: Failed to read data from storage.`

```
DEBUG mutiny-core/src/logging.rs:1172023-06-26 16:10:01.681 DEBUG [mutiny_wasm::indexed_db:179] Reading from local storage
megaStore.tsx:153 Failed to read data from storage.
setupMutinyWallet @ megaStore.tsx:153
await in setupMutinyWallet (async)
handleExisting @ megaStore.tsx:264
Promise.then (async)
handleGoodBrowser @ megaStore.tsx:283
Promise.then (async)
(anonymous) @ megaStore.tsx:293
Promise.then (async)
(anonymous) @ megaStore.tsx:251
untrack @ dev.js:434
(anonymous) @ dev.js:459
runComputation @ dev.js:696
updateComputation @ dev.js:679
runTop @ dev.js:784
runUserEffects @ dev.js:882
(anonymous) @ dev.js:851
runUpdates @ dev.js:800
completeUpdates @ dev.js:851
runUpdates @ dev.js:801
completeLoad @ dev.js:305
loadEnd @ dev.js:300
(anonymous) @ dev.js:356
Promise.then (async)
load @ dev.js:356
createResource @ dev.js:380
wrap @ dev.js:1377
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
shared.element.component.element.element @ routing.js?v=c33b05d1:66
get children @ components.jsx:65
(anonymous) @ dev.js:995
runComputation @ dev.js:696
updateComputation @ dev.js:679
createMemo @ dev.js:250
children @ dev.js:577
(anonymous) @ dev.js:995
untrack @ dev.js:434
(anonymous) @ dev.js:991
runComputation @ dev.js:696
updateComputation @ dev.js:679
createRenderEffect @ dev.js:217
provider @ dev.js:991
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
children @ components.jsx:65
(anonymous) @ dev.js:1430
untrack @ dev.js:434
Show.createMemo.name @ dev.js:1430
runComputation @ dev.js:696
updateComputation @ dev.js:679
createMemo @ dev.js:250
Show @ dev.js:1425
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
Routes @ components.jsx:64
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
get children @ root.tsx:79
get children @ megaStore.tsx:344
(anonymous) @ dev.js:995
runComputation @ dev.js:696
updateComputation @ dev.js:679
createMemo @ dev.js:250
children @ dev.js:577
(anonymous) @ dev.js:995
untrack @ dev.js:434
(anonymous) @ dev.js:991
runComputation @ dev.js:696
updateComputation @ dev.js:679
createRenderEffect @ dev.js:217
provider @ dev.js:991
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
Provider @ megaStore.tsx:342
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
get children @ root.tsx:78
get children @ ErrorBoundary.tsx:21
(anonymous) @ dev.js:1496
catchError @ dev.js:473
ErrorBoundary.createMemo.name @ dev.js:1496
runComputation @ dev.js:696
updateComputation @ dev.js:679
createMemo @ dev.js:250
ErrorBoundary @ dev.js:1489
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
ErrorBoundary @ ErrorBoundary.tsx:11
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
get children @ root.tsx:77
(anonymous) @ dev.js:1635
runComputation @ dev.js:696
updateComputation @ dev.js:679
createMemo @ dev.js:250
(anonymous) @ dev.js:1635
runComputation @ dev.js:696
updateComputation @ dev.js:679
createMemo @ dev.js:250
get children @ dev.js:1627
(anonymous) @ dev.js:995
runComputation @ dev.js:696
updateComputation @ dev.js:679
createMemo @ dev.js:250
children @ dev.js:577
(anonymous) @ dev.js:995
untrack @ dev.js:434
(anonymous) @ dev.js:991
runComputation @ dev.js:696
updateComputation @ dev.js:679
createRenderEffect @ dev.js:217
provider @ dev.js:991
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
Suspense @ dev.js:1624
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
get children @ root.tsx:76
Body @ Document.tsx:80
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
get children @ root.tsx:73
Html @ Document.tsx:20
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
Root @ root.tsx:21
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
get children @ StartClient.tsx:84
get children @ components.jsx:11
(anonymous) @ dev.js:995
runComputation @ dev.js:696
updateComputation @ dev.js:679
createMemo @ dev.js:250
children @ dev.js:577
(anonymous) @ dev.js:995
untrack @ dev.js:434
(anonymous) @ dev.js:991
runComputation @ dev.js:696
updateComputation @ dev.js:679
createRenderEffect @ dev.js:217
provider @ dev.js:991
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
Router @ components.jsx:11
(anonymous) @ dev.js:549
untrack @ dev.js:434
(anonymous) @ dev.js:545
runComputation @ dev.js:696
updateComputation @ dev.js:679
devComponent @ dev.js:556
createComponent @ dev.js:1232
StartRouter @ StartClient.tsx:76
Show 204 more frames
megaStore.tsx:265 node manager setup done
mutiny_wasm.js:3970 DEBUG mutiny-core/src/logging.rs:1172023-06-26 16:10:04.344 DEBUG [mutiny_wasm::indexed_db:179] Reading from local storage
```

**Comment by benthecarman** [comment]
Fixed backwards compat by just changing the key for storage, should just require a resync.

Removed all the places we were inserting txs into the wallet when we don't need to and just relying on the transaction broadcaster

**Review by TonyGiorgio — APPROVED** [review]
I think this has been pretty solid, there's just that (existing) bug where it has to resync upon startup. It'll still fix problems where the chain state is just too messed up at all so I'm happy with merging. Great work, we can open a ticket to fix the syncing problems if we can't figure it out yet.

**Pull request merged**
