### PR TITLE
Panic if lock has changed before reconnections

### PR DESCRIPTION
**Pull request by TonyGiorgio**
Still need to test it first, but pretty sure this is another edge case causing problems: 

Phone1: Connect Peer, Open Channel, minimizing app for 60s
Phone2: Opens, Pulls down state & channel, makes payment, closes app for 60s
Phone1: Reopens app, lock gets checked in reconnect loop, is allowed to proceed with previous state, connects to peer and force closes

It's just not safe to reconnect after lock id had changed. Longer term we can do a full storage refresh but that's a more complex procedure to bubble back up from the node reconnect logic.

### CODE REVIEW

**Review by benthecarman — APPROVED** [review]
Makes sense to me!

**Comment by TonyGiorgio** [comment]
I still need to test

**Comment by TonyGiorgio** [comment]
Been thinking about this a little bit. One thing I think we might need instead is either a continuous lock checker that starts when the wallet starts up and then panic's if the lock has changed. Something maybe that checks every 3 seconds? Maybe it's too late at that point? 

Or we change VSS to be aware of a lock ID and if a state change was attempted without having the current lock then it fails the write?

**Review by benthecarman — APPROVED** [review]
Yeah this is definitely an improvement over the previous version.

We can probably do further restrictions in the future

**Review by benthecarman — APPROVED** [review]

**Comment by TonyGiorgio** [comment]
Tested this a couple times on different browsers. 

First time it stopped it correctly. 
Screenshot 2023-12-28 at 11 17 03 PM

The second time it didn't catch it for some reason. It's possible it's due to weirdness with browser testing tolls to turn off network. It might not be disconnecting an active socket. At least the panic we put in LDK catches it. 
Screenshot 2023-12-28 at 11 21 17 PM

Over the next few days I can finish the websocket lock feature I started a few weeks ago.

**Pull request merged**
