### PR TITLE
LDK in std mode

### PR DESCRIPTION
**Pull request by TonyGiorgio**
Binary size is 9.7MB, I think it went up a little bit but not much. 

Tested almost all functionality before and after the upgrade, no issues.

### CODE REVIEW

**Comment by benthecarman** [comment]
I think with this we can start using `lightning-background-sync`, might be worth doing in a follow up though

**Comment by TonyGiorgio** [comment]
> I think with this we can start using `lightning-background-sync`, might be worth doing in a follow up though

I think the copy/paste was originally for `sync + send` stuff we had to remove.

**Comment by benthecarman** [comment]
> I think the copy/paste was originally for sync + send stuff we had to remove.

Yeah IIRC thats because the stuff we were using didn't have sync + send in no-std

**Comment by benthecarman** [comment]
We also might be able to get rid of the mutex in `utils`

**Comment by TonyGiorgio** [comment]
Getting a lot of errors switching to their background processor: 

```
585  | pub async fn process_events_async<                                                                                                                                                                                                            
     |              -------------------- required by a bound in this function                                                                                                                                                                        
...                                                                                                                                                                                                                                                  
603  |     CM: 'static + Deref<Target = ChannelManager<CW, T, ES, NS, SP, F, R, L>> + Send + Sync,                                                                                                                                                   
     |                                                                                ^^^^ required by this bound in `process_events_async`                                                                                                          
help: consider further restricting this bound                                                                                                                                                                                                        
     |                                                                                                                                                                                                                                               
177  | impl<S: MutinyStorage + std::marker::Sync> Node<S> {                                                                                                                                                                                          
     |                       +++++++++++++++++++                                                                                                                                                                                                     
                                                                                                                                                                                                                                                     
error[E0277]: `S` cannot be sent between threads safely                                                                                                                                                                                              
    --> mutiny-core/src/node.rs:493:21                                                                                                                                                                                                               
     |                                                                                                                                                                                                                                               
489  |                 if let Err(e) = process_events_async(                                                                                                                                                                                         
     |                                 -------------------- required by a bound introduced by this call                                                                                                                                              
...                                                                                                                                                                                                                                                  
493  |                     background_processor_channel_manager.clone(),                                                                                                                                                                             
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `S` cannot be sent between threads safely                                                                                                                                    
     |                                                                                                                            
```

Which comes from our own trait: 
```
pub trait MutinyStorage: Clone + Sized + 'static {
```

and I suppose we have probably done quite a bit of that everywhere. Was that due to the Mutex type we were using or something? I thought really comes from the fact that we're limited to single threaded in wasm anyways.

**Comment by benthecarman** [comment]
Okay let's just ignore it for now then, can attempt it later.

**Review by benthecarman — APPROVED** [review]

**Pull request merged**
