### PR TITLE
Add public and private zaps

### PR DESCRIPTION
**Pull request by benthecarman**
This was _almost_ very simple, but sadly doing private zaps with a NIP-07 extension isn't very well supported. The way clients generate the random npub is deterministic from the user's nsec, but since we don't have the user's nsec, we cannot do this. Private zaps will still work, we can just randomly generate the key, the problem is if we see the event in the future, we won't be able to decrypt it ourselves.

### CODE REVIEW

**Comment by TonyGiorgio** [comment]
> the problem is if we see the event in the future, we won't be able to decrypt it ourselves.

We'll still have some reference for it inside of mutiny, right? And for private zaps, the receiver will still see it was from us?

**Comment by TonyGiorgio** [comment]
> if I do a private zap Ben -> Tony, if I open up in Damus I will see you were private zapped

That's fine IMO, I don't care that much if we're limited here. But will it still show up in Mutiny is more my question.

**Comment by benthecarman** [comment]
> That's fine IMO, I don't care that much if we're limited here. But will it still show up in Mutiny is more my question.

yes

**Comment by TonyGiorgio** [comment]
needs rebase

**Comment by benthecarman** [comment]
New release of rust-nostr came out so was able to simplify

**Review by TonyGiorgio — APPROVED** [review]

**Pull request merged**
