### PR TITLE
Move channel config load after watch_channel

### PR DESCRIPTION
**Pull request by benthecarman**
We weren't following the docs for the channel manager where we shouldn't change the channel config until after we've called `watch_channel`. This should fix the `unreachable` @futurepaul was running into

https://docs.rs/lightning/latest/lightning/ln/channelmanager/struct.ChannelManagerReadArgs.html

### CODE REVIEW

**Review by futurepaul — APPROVED** [review]
worked!

**Review by TonyGiorgio — CHANGES_REQUESTED** [review]
I don't see why these would be triggering at all. There's some bug here then because we haven't changed the channel config in a very long time. I agree we should move the code, however something is wrong with this code if it is being triggered without a config change.

**Comment by benthecarman** [comment]
The config changed with the LSPS changes

**Comment by TonyGiorgio** [comment]
It has? What has it changed to? The accept under pay thing? I guess that makes sense.  Was this @futurepaul 's first time using the wallet since that update? 

How was this not caught in testing? I used an existing wallet when I tested.

**Comment by benthecarman** [comment]
Added a commit to only set `accept_underpaying_htlcs` with LSPS

**Comment by TonyGiorgio** [comment]
Okay makes sense. I think it happened with someone else last week too. Was having a random panic.

**Review by TonyGiorgio — APPROVED** [review]

**Pull request merged**
