### PR TITLE
Detect subscribed in backend

### PR DESCRIPTION
**Pull request by benthecarman**
Detects if subscribed and will save nwc profiles to vss if you have mutiny+

### CODE REVIEW

**Comment by benalleng** [comment]
Will this remove the need for the frontend to store sub-status in localStorage?

**Comment by benthecarman** [comment]
> Is NWC profiles being saved for everyone now or just those being subscribed?

just subscribed

**Comment by TonyGiorgio** [comment]
What's going to happen to people that stopped subscribing? Is their data going to be deleted? How is it fetched when they stopped subscribing?

**Comment by TonyGiorgio** [comment]
I just really don't want to see anything stored in VSS besides critical data until we have a better handle on storage stuff.

**Comment by benthecarman** [comment]
> I just really don't want to see anything stored in VSS besides critical data until we have a better handle on storage stuff.

yeah i understand that, this should handle all the cases but we can leave it out for now

**Review by TonyGiorgio — APPROVED** [review]

**Pull request merged**
