### PR TITLE
Change archive contact to delete contact

### PR DESCRIPTION
**Pull request by benthecarman**
Previous iteration just archived which made things ugly for the front end afterwards. This is cleaner and makes thing simpler for everyone

### CODE REVIEW

**Comment by benthecarman** [comment]
This doesn't work well with fedimint labels, not sure what the status on storage for fedimint stuff is cc @TonyGiorgio

**Comment by TonyGiorgio** [comment]
> This doesn't work well with fedimint labels, not sure what the status on storage for fedimint stuff is cc @TonyGiorgio

Not sure. I'll look into it more later.

**Comment by benthecarman** [comment]
can revisit this now that fedimint has moved to indexed db

**Review by TonyGiorgio — APPROVED** [review]
I think this will work just fine with the fedimint stuff. Just rebase and test but code looks functional.

**Comment by benthecarman** [comment]
Tested and this now works with fedimint payments

**Pull request merged**
